name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up JDK 17
      uses: actions/setup-java@v4.2.2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Maven
      uses: actions/setup-java@v4.2.2
      with:
        java-version: '17'
        distribution: 'temurin'
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Snyk Security Scan (pre-build)
      run: snyk test --file=pom.xml --json-file-output=snyk-pre-build-results.json
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Build with Maven
      run: mvn clean install

    - name: Snyk Security Scan (post-build)
      run: snyk test --all-projects --json-file-output=snyk-post-build-results.json
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Run tests
      run: mvn test

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2.3.0
      with:
        args: >
          -Dsonar.projectKey=votre_projet
          -Dsonar.organization=votre_organisation
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          -Dsonar.java.binaries=target/classes
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Publish Snyk pre-build scan results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: snyk-pre-build-results
        path: snyk-pre-build-results.json

    - name: Publish Snyk post-build scan results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: snyk-post-build-results
        path: snyk-post-build-results.json

    - name: Publish test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/surefire-reports/

    - name: Clean up
      run: mvn clean
