name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Check JAVA_HOME
      run: echo $JAVA_HOME
        
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up JDK 17
      uses: actions/setup-java@v4.2.2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2.3.0
      with:
        args: >
          -Dsonar.projectKey=n-i_github
          -Dsonar.organization=n-i
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          -Dsonar.java.binaries=target/classes
          -X
      env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


    - name: Snyk Security Scan
      run: |
       docker pull snyk/snyk:maven-3-jdk-17
       docker run -e SNYK_TOKEN="${{ secrets.SNYK_TOKEN }}" -v "$(pwd):/project" snyk/snyk:maven-3-jdk-17 test --org=60010d4c-52e2-4831-beb5-ae127cd1af0d --all-projects --docker

