name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Check JAVA_HOME
      run: echo $JAVA_HOME
        
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up JDK 17
      uses: actions/setup-java@v4.2.2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2.3.0
      with:
        args: >
          -Dsonar.projectKey=n-i_github
          -Dsonar.organization=n-i
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          -Dsonar.java.binaries=target/classes
          -X
      env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


    # Ajouter Snyk CLI
    - name: Install Snyk CLI
      run: npm install -g snyk

    # Exécuter les tests Snyk
    - name: Run Snyk test in debug mode
      env:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk test -d


    - name: Deploy Application
      run: mvn deploy
