name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Check JAVA_HOME
      run: echo $JAVA_HOME
        
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up JDK 17
      uses: actions/setup-java@v4.2.2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Give execute permission to mvnw
      run: chmod +x mvnw
        
    - name: Build with Maven
      run: ./mvnw clean install

    - name: Run tests
      run: ./mvnw test

    - name: Snyk Security Scan
      uses: snyk/actions/setup@0.4.0
      with:
        version: '1.1094.0'
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Snyk Test
      run: snyk test --file=pom.xml
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2.3.0
      with:
        args: >
          -Dsonar.projectKey=n-i_github
          -Dsonar.organization=n-i
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          -Dsonar.java.binaries=target/classes
          -X
      env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
