
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Snyk Security Scan (code)
      run: |
        docker pull snyk/snyk-cli
        docker run -e SNYK_TOKEN="${{ secrets.SNYK_TOKEN }}" -v "$(pwd):/project" snyk/snyk-cli test /project --file=package.json --json-file-output=snyk-code-results.json

    - name: Set up JDK 17
      uses: actions/setup-java@v4.2.2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean install

    - name: Snyk Security Scan (dependencies)
      run: |
        docker pull snyk/snyk:maven-3-jdk-17
        docker run -e SNYK_TOKEN="${{ secrets.SNYK_TOKEN }}" -v "$(pwd):/project" snyk/snyk:maven-3-jdk-17 test --all-projects --json-file-output=snyk-dependencies-results.json

    - name: Run tests
      run: mvn test

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2.3.0
      with:
        args: >
          -Dsonar.projectKey=votre_projet
          -Dsonar.organization=votre_organisation
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          -Dsonar.java.binaries=target/classes
      env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Publish Snyk code scan results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: snyk-code-results
        path: snyk-code-results.json

    - name: Publish Snyk dependencies scan results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: snyk-dependencies-results
        path: snyk-dependencies-results.json

    - name: Clean up
      run: mvn clean
