name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up JDK 17
      uses: actions/setup-java@v4.2.2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2.3.0
      with:
        args: >
          -Dsonar.projectKey=n-i
          -Dsonar.organization=Niasrb
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    #- name: Install Snyk CLI
    #  run: |
#        curl -o- https://static.snyk.io/cli/latest/snyk-linux.tar.gz | tar xz -C /usr/local/bin snyk

 #   - name: Snyk Vulnerability Scan
   #   env:
    #    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
     # run: snyk test --all-projects

   # - name: Deploy Application
    #  run: mvn deploy
